version: "1.0"
services:
  portainer-ce:
    image: portainer/portainer-ce 
    container_name: portainer-ce
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes/portainer_data:/data portainer/portainer-ce:latest
    restart: always